// Vectors-driven testbench for spirix_addsub at FRAC=24, EXP=8.
// Reads verilog/vectors.txt (generated by gen_addsub_vectors), drives the
// DUT, classifies the result, and compares against the gold model.
//
// State codes (must match gen_addsub_vectors.rs):
//   0 Normal, 1 Zero, 2 PosVan, 3 NegVan, 4 PosExp, 5 NegExp, 6 Inf, 7 Undef.

`timescale 1ns/1ps
module tb_random;
    localparam FRAC = 24;
    localparam EXP  = 8;
    localparam [EXP-1:0] AMB = {EXP{1'b0}}; // AMBIG = 0 (all-zeros bit pattern)

    reg signed [FRAC-1:0] a_frac, b_frac;
    reg        [EXP-1:0]  a_exp,  b_exp;
    reg                    sub;
    wire signed [FRAC-1:0] r_frac;
    wire        [EXP-1:0]  r_exp;

    spirix_addsub #(.FRAC_BITS(FRAC), .EXP_BITS(EXP)) dut(
        .a_frac(a_frac), .a_exp(a_exp),
        .b_frac(b_frac), .b_exp(b_exp),
        .sub(sub),
        .result_frac(r_frac), .result_exp(r_exp)
    );

    // ── State classifier in Verilog (mirrors lib.rs::classify) ──
    function [3:0] classify;
        input [FRAC-1:0] storage; input [EXP-1:0] e;
        reg [FRAC-1:0] s; reg msb; integer i; integer count;
        begin
            s = storage;
            if (e !== AMB) begin classify = 0; end // Normal
            else if (s === {FRAC{1'b0}}) classify = 1; // Zero
            else if (&s)               classify = 6; // Infinity
            else begin
                msb = s[FRAC-1];
                count = 1;
                for (i = FRAC-2; i >= 0; i = i - 1) begin
                    if (s[i] === msb) count = count + 1;
                    else i = -1; // break out of loop
                end
                if (count == 1) begin
                    classify = (msb == 1'b0) ? 4 : 5; // pos/neg exploded
                end else if (count == 2) begin
                    classify = (msb == 1'b0) ? 2 : 3; // pos/neg vanished
                end else begin
                    classify = 7; // Undefined
                end
            end
        end
    endfunction

    integer fd, line;
    integer total, exact, ulp1, state_match_undef, fail;

    reg [FRAC-1:0]    a_in, b_in, gold_frac;
    integer           a_e_in, b_e_in, gold_e_in, sub_in, gold_st_in;
    reg [EXP-1:0]     gold_exp;
    reg [3:0] dut_state, expected_state;

    integer fail_examples;

    initial begin
        fd = $fopen("verilog/vectors.txt", "r");
        if (fd == 0) begin
            $display("FATAL: cannot open verilog/vectors.txt");
            $finish;
        end

        total = 0; exact = 0; ulp1 = 0; state_match_undef = 0; fail = 0;
        fail_examples = 0;

        line = 0;
        while (!$feof(fd)) begin
            integer rc;
            rc = $fscanf(fd, "%h %d %h %d %d %h %d %d\n",
                         a_in, a_e_in, b_in, b_e_in, sub_in,
                         gold_frac, gold_e_in, gold_st_in);
            if (rc !== 8) begin
                if (!$feof(fd)) $display("WARN: parse rc=%0d at line %0d", rc, line);
                ; // tail
            end else begin
                line = line + 1;
                a_frac = a_in;
                a_exp  = a_e_in[EXP-1:0];
                b_frac = b_in;
                b_exp  = b_e_in[EXP-1:0];
                sub    = sub_in[0];
                gold_exp = gold_e_in[EXP-1:0];
                expected_state = gold_st_in[3:0];
                #1;

                dut_state = classify(r_frac, r_exp);

                total = total + 1;
                if (expected_state === 4'd7) begin
                    // Undefined: match any LSBC≥3 result regardless of bit pattern
                    if (dut_state === 4'd7 && r_exp === AMB) begin
                        state_match_undef = state_match_undef + 1;
                        exact = exact + 1;
                    end else begin
                        fail = fail + 1;
                        if (fail_examples < 40) begin
                            $display("FAIL[%0d]: expected Undefined, got state=%0d (%h,%0d) for (%h,%0d) %s (%h,%0d)",
                                     line, dut_state, r_frac, r_exp,
                                     a_in, a_e_in, sub_in ? "-" : "+", b_in, b_e_in);
                            fail_examples = fail_examples + 1;
                        end
                    end
                end else begin
                    if (r_frac === gold_frac && r_exp === gold_exp) begin
                        exact = exact + 1;
                    end else if (expected_state === 4'd0 && dut_state === 4'd0
                                 && r_exp === gold_exp
                                 && ((r_frac - gold_frac == 24'sd1) ||
                                     (gold_frac - r_frac == 24'sd1))) begin
                        ulp1 = ulp1 + 1;
                        if (ulp1 <= 5) begin
                            $display("  ULP1[%0d]: (%h,%0d) %s (%h,%0d) → got %h want %h (diff=%0d)",
                                     line, a_in, a_e_in, sub_in ? "-" : "+",
                                     b_in, b_e_in, r_frac, gold_frac,
                                     $signed(r_frac) - $signed(gold_frac));
                        end
                    end else begin
                        fail = fail + 1;
                        if (fail_examples < 40) begin
                            $display("FAIL[%0d]: (%h,%0d) %s (%h,%0d) → got (%h,%0d) want (%h,%0d) [exp_state=%0d, dut_state=%0d]",
                                     line,
                                     a_in, a_e_in, sub_in ? "-" : "+", b_in, b_e_in,
                                     r_frac, r_exp, gold_frac, gold_exp,
                                     expected_state, dut_state);
                            fail_examples = fail_examples + 1;
                        end
                    end
                end
            end
        end
        $fclose(fd);

        $display("");
        $display("Total:        %0d", total);
        $display("Exact:        %0d  (%0d undef-state matches)", exact, state_match_undef);
        $display("1-ULP off:    %0d  (Spirix-vs-IEEE rounding divergence in subtraction)", ulp1);
        $display(">1-ULP fail:  %0d", fail);
        if (fail == 0) $display("OK");
        else $display("FAILED");
        $finish;
    end
endmodule
