[package]
name = "spirix-paper-comparison"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gen_addsub_vectors"
path = "src/bin/gen_addsub_vectors.rs"

[[bin]]
name = "gen_mul_vectors"
path = "src/bin/gen_mul_vectors.rs"

[[bin]]
name = "gen_div_vectors"
path = "src/bin/gen_div_vectors.rs"

[[bin]]
name = "gen_sqrt_vectors"
path = "src/bin/gen_sqrt_vectors.rs"

[[bin]]
name = "gen_div_p4_bram"
path = "src/bin/gen_div_p4_bram.rs"

[dependencies]
